/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Uİ;

import javax.swing.JOptionPane;
import model.UserAccount;
import util.SessionManager;

/**
 *
 * @author Mustafa AVCI
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        applyRolePermissions();
        initUserInfo();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Oturumu kapat
                SessionManager.getInstance().logout();

                // Login ekranını tekrar aç
                new LoginScreen().setVisible(true);
            }
        });

    }

    private void initUserInfo() {
        SessionManager sm = SessionManager.getInstance();

        if (sm.isLoggedIn()) {
            lblUserInfo.setText(
                    "Welcome : "
                    + sm.getCurrentUsername()
                    + " (" + sm.getCurrentUserRole() + ")"
            );
        } else {
            lblUserInfo.setText("Logged in as:");
        }
    }

    private void applyRolePermissions() {
        SessionManager sm = SessionManager.getInstance();

        if (!sm.isLoggedIn()) {
            JOptionPane.showMessageDialog(this, "User session not found. Please log in.");
            new LoginScreen().setVisible(true);
            this.dispose();
            return;
        }

        // Önce her şeyi kapat
        btnStaff.setEnabled(false);
        btnPatient.setEnabled(false);
        btnSurgery.setEnabled(false);
        btnSurgeryMaterial.setEnabled(false);
        btnMaterial.setEnabled(false);
        btnStorage.setEnabled(false);
        btnInventory.setEnabled(false);
        btnUserManagement.setEnabled(false);
        btnAddUser.setEnabled(false);
        btnSurgeryStaff.setEnabled(false); 

        // Gizle (admin dışı)
        btnUserManagement.setVisible(false);
        btnAddUser.setVisible(false);
        btnSurgeryStaff.setVisible(false);  

        // ADMIN → her şey açık
        if (sm.isAdmin()) {
            btnStaff.setEnabled(true);
            btnPatient.setEnabled(true);
            btnSurgery.setEnabled(true);
            btnSurgeryMaterial.setEnabled(true);
            btnMaterial.setEnabled(true);
            btnStorage.setEnabled(true);
            btnInventory.setEnabled(true);

            btnUserManagement.setEnabled(true);
            btnUserManagement.setVisible(true);

            btnAddUser.setEnabled(true);
            btnAddUser.setVisible(true);

            btnSurgeryStaff.setEnabled(true);   
            btnSurgeryStaff.setVisible(true); 

            return;
        }

        // DOCTOR
        if (sm.isDoctor()) {
            btnPatient.setEnabled(true);
            btnSurgery.setEnabled(true);
            btnSurgeryMaterial.setEnabled(true);
            btnSurgeryStaff.setVisible(true);
            return;
        }

        // NURSE
        if (sm.isNurse()) {
            btnSurgeryMaterial.setEnabled(true);
            return;
        }

        // STORAGE MANAGER
        if (sm.isStorageManager()) {
            btnMaterial.setEnabled(true);
            btnStorage.setEnabled(true);
            btnInventory.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnStaff = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnSurgery = new javax.swing.JButton();
        btnMaterial = new javax.swing.JButton();
        btnStorage = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnSurgeryMaterial = new javax.swing.JButton();
        lblUserInfo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnUserManagement = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnSurgeryStaff = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu Screen");
        setMaximumSize(new java.awt.Dimension(780, 585));
        setMinimumSize(new java.awt.Dimension(780, 585));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(780, 585));
        jPanel1.setMinimumSize(new java.awt.Dimension(780, 585));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 585));

        btnStaff.setBackground(new java.awt.Color(255, 153, 204));
        btnStaff.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnStaff.setText("Staff Management");
        btnStaff.setMaximumSize(new java.awt.Dimension(220, 100));
        btnStaff.setMinimumSize(new java.awt.Dimension(220, 100));
        btnStaff.setPreferredSize(new java.awt.Dimension(220, 100));
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });

        btnPatient.setBackground(new java.awt.Color(255, 153, 153));
        btnPatient.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPatient.setText("Patient Management");
        btnPatient.setMaximumSize(new java.awt.Dimension(220, 100));
        btnPatient.setMinimumSize(new java.awt.Dimension(220, 100));
        btnPatient.setPreferredSize(new java.awt.Dimension(220, 100));
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });

        btnSurgery.setBackground(new java.awt.Color(153, 255, 153));
        btnSurgery.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSurgery.setText("Surgery Management");
        btnSurgery.setMaximumSize(new java.awt.Dimension(220, 100));
        btnSurgery.setMinimumSize(new java.awt.Dimension(220, 100));
        btnSurgery.setPreferredSize(new java.awt.Dimension(220, 100));
        btnSurgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurgeryActionPerformed(evt);
            }
        });

        btnMaterial.setBackground(new java.awt.Color(255, 153, 153));
        btnMaterial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMaterial.setText("Material Transaction");
        btnMaterial.setMaximumSize(new java.awt.Dimension(220, 100));
        btnMaterial.setMinimumSize(new java.awt.Dimension(220, 100));
        btnMaterial.setPreferredSize(new java.awt.Dimension(220, 100));
        btnMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialActionPerformed(evt);
            }
        });

        btnStorage.setBackground(new java.awt.Color(153, 204, 255));
        btnStorage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnStorage.setText("Storage Location ");
        btnStorage.setMaximumSize(new java.awt.Dimension(220, 100));
        btnStorage.setMinimumSize(new java.awt.Dimension(220, 100));
        btnStorage.setPreferredSize(new java.awt.Dimension(220, 100));
        btnStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStorageActionPerformed(evt);
            }
        });

        btnInventory.setBackground(new java.awt.Color(153, 255, 153));
        btnInventory.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnInventory.setText("Inventory Management");
        btnInventory.setMaximumSize(new java.awt.Dimension(220, 100));
        btnInventory.setMinimumSize(new java.awt.Dimension(220, 100));
        btnInventory.setPreferredSize(new java.awt.Dimension(220, 100));
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });

        btnSurgeryMaterial.setBackground(new java.awt.Color(153, 204, 255));
        btnSurgeryMaterial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSurgeryMaterial.setText("Surgery Material");
        btnSurgeryMaterial.setMaximumSize(new java.awt.Dimension(220, 100));
        btnSurgeryMaterial.setMinimumSize(new java.awt.Dimension(220, 100));
        btnSurgeryMaterial.setPreferredSize(new java.awt.Dimension(220, 100));
        btnSurgeryMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurgeryMaterialActionPerformed(evt);
            }
        });

        lblUserInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUserInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblUserInfo.setText("HOSPITAL MANAGEMENT");

        btnLogout.setBackground(new java.awt.Color(204, 0, 0));
        btnLogout.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("EXIT");
        btnLogout.setBorderPainted(false);
        btnLogout.setMaximumSize(new java.awt.Dimension(220, 100));
        btnLogout.setMinimumSize(new java.awt.Dimension(220, 100));
        btnLogout.setPreferredSize(new java.awt.Dimension(220, 100));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnChangePassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnChangePassword.setText("Change Password");
        btnChangePassword.setMaximumSize(new java.awt.Dimension(220, 100));
        btnChangePassword.setMinimumSize(new java.awt.Dimension(220, 100));
        btnChangePassword.setPreferredSize(new java.awt.Dimension(220, 100));
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnUserManagement.setBackground(new java.awt.Color(153, 204, 255));
        btnUserManagement.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUserManagement.setText("User Management");
        btnUserManagement.setMaximumSize(new java.awt.Dimension(220, 100));
        btnUserManagement.setMinimumSize(new java.awt.Dimension(220, 100));
        btnUserManagement.setPreferredSize(new java.awt.Dimension(220, 100));
        btnUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementActionPerformed(evt);
            }
        });

        btnAddUser.setBackground(new java.awt.Color(51, 51, 255));
        btnAddUser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUser.setText("Add User");
        btnAddUser.setMaximumSize(new java.awt.Dimension(220, 100));
        btnAddUser.setMinimumSize(new java.awt.Dimension(220, 100));
        btnAddUser.setPreferredSize(new java.awt.Dimension(220, 100));
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnSurgeryStaff.setBackground(new java.awt.Color(255, 153, 204));
        btnSurgeryStaff.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSurgeryStaff.setText("Surgery Staff Manage");
        btnSurgeryStaff.setMaximumSize(new java.awt.Dimension(220, 100));
        btnSurgeryStaff.setMinimumSize(new java.awt.Dimension(220, 100));
        btnSurgeryStaff.setPreferredSize(new java.awt.Dimension(220, 100));
        btnSurgeryStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurgeryStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSurgeryMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSurgery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUserInfo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSurgeryStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnStorage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnInventory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSurgeryStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSurgery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSurgeryMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSurgeryStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurgeryStaffActionPerformed
        // Önce yetki kontrolü
        if (!SessionManager.getInstance().isAdmin()) {
            JOptionPane.showMessageDialog(this, "Welcome");
            return;
        }

        new SurgeryStaffManagement().setVisible(true);
    }//GEN-LAST:event_btnSurgeryStaffActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        new AddUserAccount().setVisible(true);

    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementActionPerformed
        // TODO add your handling code here:
        new UserAccountManagement().setVisible(true);
    }//GEN-LAST:event_btnUserManagementActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        new ChangePasswordScreen().setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Do you want to exit?",
            "Exit",
            JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {

            SessionManager.getInstance().logout();
            new LoginScreen().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSurgeryMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurgeryMaterialActionPerformed
        // TODO add your handling code here:
        new SurgeryMateriall().setVisible(true);
    }//GEN-LAST:event_btnSurgeryMaterialActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        // TODO add your handling code here:
        new InventoryManagement().setVisible(true);
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStorageActionPerformed
        // TODO add your handling code here:
        new StorageLocationManagement().setVisible(true);
    }//GEN-LAST:event_btnStorageActionPerformed

    private void btnMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialActionPerformed
        // TODO add your handling code here:
        new MaterialTransaction().setVisible(true);
    }//GEN-LAST:event_btnMaterialActionPerformed

    private void btnSurgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurgeryActionPerformed
        // TODO add your handling code here:
        new SurgeryManagement().setVisible(true);
    }//GEN-LAST:event_btnSurgeryActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        new PatientManagementt().setVisible(true);
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        // TODO add your handling code here:
        new StaffManagement().setVisible(true);
    }//GEN-LAST:event_btnStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMaterial;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnStaff;
    private javax.swing.JButton btnStorage;
    private javax.swing.JButton btnSurgery;
    private javax.swing.JButton btnSurgeryMaterial;
    private javax.swing.JButton btnSurgeryStaff;
    private javax.swing.JButton btnUserManagement;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUserInfo;
    // End of variables declaration//GEN-END:variables
}
